### ISSUE TITLE
Remove editor support

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/post-type-archive-settings#5]
I think the editor support should be optional.

**Comment by haroldangenent** [comment]
This is already optional, you can easily remove it when it's not necessary using the supplied hooks. 

Since it was basically the reason for creating this library, `editor` support is on 'by default'. While it might not only be used in this way these days, this default cannot be changed without fully breaking backwards compat, which doesn't seem worth it at this time.

I'll have to close this issue as invalid.
